name       : python-precis_i18n
version    : 1.0.0
release    : 3
source     :
    - https://files.pythonhosted.org/packages/1f/05/799c3c2c22b9c80f67a8cd4bd772804c6242ab4319974aff2b8d689755f8/precis_i18n-1.0.0.tar.gz : 227ac196b8a31b1209030bfbe90616dd375be946e0a9403349dd45851adf503e
license    : MIT
component  : programming.python
summary    : The PRECIS framework makes internationalized user names and passwords
    safer for use by applications.
description: |
    If you want your application to accept unicode user names and passwords, you must be careful in how you validate and compare them. The PRECIS framework makes internationalized user names and passwords safer for use by applications. PRECIS profiles transform unicode strings into a canonical form, suitable for comparison.
build      : |
    %python3_setup
install    : |
    %python3_install
