name       : python-precis_i18n
version    : 1.0.4
release    : 6
source     :
    - https://github.com/byllyfish/precis_i18n/archive/refs/tags/v1.0.4.tar.gz : 7025607a5dc2d11b2cde4a744834cbdff4d52462c7e1034a7f6220286a53a181
homepage   : https://github.com/byllyfish/precis_i18n
license    : MIT
component  : programming.python
summary    : Python3 implementation of the PRECIS framework (RFC 8264/8265/8266)
description: |
    If you want your application to accept unicode user names and passwords, you must be careful in how you validate and compare them. The PRECIS framework makes internationalized user names and passwords safer for use by applications. PRECIS profiles transform unicode strings into a canonical form, suitable for comparison.
builddeps  :
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
