name       : python-precis_i18n
version    : 1.0.3
release    : 4
source     :
    - https://files.pythonhosted.org/packages/source/p/precis_i18n/precis_i18n-1.0.3.tar.gz : df5f3f7a444ca024d0677783336a194c27656f391d76f026dec5947e3f3acbe1
homepage   : https://github.com/byllyfish/precis_i18n
license    : MIT
component  : programming.python
summary    : Python3 implementation of the PRECIS framework (RFC 8264/8265/8266)
description: |
    If you want your application to accept unicode user names and passwords, you must be careful in how you validate and compare them. The PRECIS framework makes internationalized user names and passwords safer for use by applications. PRECIS profiles transform unicode strings into a canonical form, suitable for comparison.
builddeps  :
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
